### PR TITLE
Move Wiki to /docs folder and update links

### PR DESCRIPTION
**Pull request by adamalesandro**
I updated the links and added a listing of all the pages now at the bottom of the index page.

### CODE REVIEW

**Comment by joukevandermaas** [comment]
Thanks so much for this! Can you enable publishing the `/docs` directory to github pages from your fork? Then the website should be deployed at http://adamalesandro.github.io/saule and I can take a look at it there too.

**Comment by adamalesandro** [comment]
Would you like me to add page headers and some basic nav to each page?
i.e.
## Pagination

[Back to home](index)

**Comment by joukevandermaas** [comment]
Yeah probably. I think that will be nice. It looks great so far!

**Comment by adamalesandro** [comment]
Should be good now, let me know if you would like any other changes.

**Comment by joukevandermaas** [comment]
Thanks a lot for this @adamalesandro! I'll merge this and enable publishing it to github pages.

**Pull request merged**
