### PR TITLE
Remove links property assignment that unused and overwritten

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by joukevandermaas** [comment]
@bjornharrtell I think this is obsolete with #149?

**Comment by bjornharrtell** [comment]
The old `ResourceSerializer` is still there so might still be relevant, if you are not intending to remove it in short term?

**Comment by joukevandermaas** [comment]
It is not there anymore, we removed it. The new one is so much better! :smile:

**Comment by bjornharrtell** [comment]
Great to hear it and I look forward to try it out! :) Closing.

**Pull request closed without merging**
