### PR TITLE
Convert case for relationship as well in ResourceDeserializer

### PR DESCRIPTION
**Pull request by bxh**

### CODE REVIEW

**Comment by joukevandermaas** [comment]
Thanks very much for contributing! Can you add a test that would fail without this change to prevent regressions?

**Comment by bxh** [comment]
Done. If you are pleased with the change, could you cut a new patch release after? Thanks.

**Comment by joukevandermaas** [comment]
Sure. I'll do that in the coming couple days. Thanks again!

**Comment by joukevandermaas** [comment]
Oh, and could you please rebase this on `master` so I can merge it?

**Comment by bxh** [comment]
Updated.

**Comment by bxh** [comment]
Could you cut a new release that includes this fix? :)

**Comment by joukevandermaas** [comment]
@bxh done! sorry for the delay.

**Comment by bxh** [comment]
No worries at all. Thanks for prompt response!

**Pull request merged**
