### PR TITLE
Do not require Accept header

### PR DESCRIPTION
**Pull request by bjornharrtell**
My take on https://github.com/joukevandermaas/saule/issues/100 and https://github.com/joukevandermaas/saule/issues/146.

### CODE REVIEW

**Comment by joukevandermaas** [comment]
Thanks for this!

I understood the requirements from #100 and #146 as follows:

1. If the client does not send a request body, it does not need to send a `Content-Type` header
2. The client does not need to send an accept header
3. If the client *does* send an accept header, it must be `application/vnd.api+json` without any media type parameters

I don't really see these reflected in this PR though. My understanding of the code is these rules:

4. The client does not need to send an accept header for `GET` and `DELETE` requests
5. Other requests must have an accept header, and it must be `application/vnd.api+json` without any media type parameters
6. Nothing about `Content-Type` in the diff.

4 and 5 don't make much sense to me, because I thought the `Accept` header was about the `content-type` of the *response*, not the request. It makes sense to validate it always (if it exists).

If I misunderstood something, please let me know!

**Comment by bjornharrtell** [comment]
You are absolutely correct, for some reason I mixed up these headers logically when taking a stab at this.

I suggest a more simple change to simply let requests through that have no `application/vnd.api+json` `Accept` header at all. For `Content-Type` I'm not sure there is an issue at all.

**Comment by bjornharrtell** [comment]
Reworked as suggested. I hope it makes sense this time.

**Comment by joukevandermaas** [comment]
Looks good! thanks!

**Pull request merged**
