### PR TITLE
Related resources

### PR DESCRIPTION
**Pull request by yohanmishkin**
Here's a spike on #126. Let me know if you feel like it might be worth iterating on and polishing, but I used [JSON API Fetching Includes](http://jsonapi.org/format/#fetching-includes) for reference.

### CODE REVIEW

**Comment by yohanmishkin** [comment]
Broken

**Comment by joukevandermaas** [comment]
This looks great so far! I'd very much appreciate more work on this. You'll probably have to rebase this on the latest changes in `master`.

I'll review in more detail later this week if possible.

**Comment by yohanmishkin** [comment]
Awesome, trying to rebase now. Some strangeness with the line endings is making it a bit tricky.

**Comment by bjornharrtell** [comment]
@joukevandermaas why was this closed? I'm currently missing this so if you need help resurrecting it I might be able to.

**Comment by joukevandermaas** [comment]
@bjornharrtell I don't know why this was closed, but I'd very much appreciate you picking it up again if you have time. Thanks!

**Comment by bjornharrtell** [comment]
Having a hard time with Git and line ending issues.. I see you had some problems too that #135 aimed to fix but as of yet I have not been able to clone the repo without some files getting autoconverted.

**Comment by bjornharrtell** [comment]
Removing .gitattributes *before* making a clone works for me.

**Comment by yohanmishkin** [comment]
Yeah, I got stuck there too. Thanks for picking up @bjornharrtell !

**Comment by bjornharrtell** [comment]
Thanks for the implementation @yohanmishkin. :) I hope to have use for it in the coming months.

**Pull request closed without merging**
