### PR TITLE
Support belongsTo relationships when data is null

### LINKED ISSUE #123: Deserializing null relationships
Saule is fantastic! Thanks a million for all the work. Quick question:

My application is posting the following json to a Saule resource with a relationship and the deserializer is unable to deserialize the review object because its data is null. Any thoughts

```
{
  "data": {
    "attributes": {
      "name": null,
      "price": 12
    },
    "relationships": {
      "review": {
        "data": null
      }
    },
    "type": "book"
  }
}
```
The BookResource look like this:

```
public class BookResource : ApiResource
{
    public BookResource()
    {
        WithId("Id");
        Attribute("Name");
        Attribute("Price");
        HasMany<ReviewResource>("Review");
    }
}
```
I receive an "Object reference not set to an instance of an object." error during deserialization of the book's review. 

Is there a simple way to override the deserializer to a null check perhaps or am I maybe doing something blatantly wrong?

### PR DESCRIPTION
**Pull request by goo32**
Fixes #123

### CODE REVIEW

**Comment by goo32** [comment]
Would it be possible to cut a release that would include this fix?

**Comment by joukevandermaas** [comment]
@goo32 I'll try to do that this week. In the meantime, the latest pre-release includes this fix.

**Comment by goo32** [comment]
My apologies... I didn't realize there was a pre-release. I'll test my stuff out with the latest. Thanks!

**Comment by joukevandermaas** [comment]
NP. Any commit on `master` publishes a new pre-release, so the latest pre-release is always up to date with whatever is in `master`.

**Pull request merged**
